name: Mirroring

on: 
  push:
    branches:
      - main

jobs:
  to_git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-CPP-500-TLS-5-2-rtype-baptiste.allex.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
