name: cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build on ubuntu
        run: ./install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: rtype
